### ISSUE TITLE
absolute importを出来るようにしたい

### ISSUE THREAD

**Issue by hppRC** [knights-dev/knights#48]
srcディレクトリ下にたくさんコンポーネント が生えると思うので、早めに簡潔にimport出来るようにしておきたい。

## 想定変更箇所
1. tsconfig.jsonに以下のような感じで path alias を設定

```
{
    "compilerOptions": {
...
        "baseUrl": ".",
        "paths": { "src/*": ["src/*"] }
    }
}
```

webpack.configにresolveの時のオプションを追加

```
...
    resolve: {
        extensions: ['.ts', '.tsx', '.js'],
        alias: {
            src: path.resolve(__dirname, 'src'),
        },
    },
...
```
これで以下のようにimport出来る。

```javascript

import { ArrowLine } from 'src/components/nodes';

```

aliasを適当に生やせばもっと短く出来るので、path alias は今後の開発次第でさらに細かくしてもいいかも

**Comment by hppRC** [comment]
よさそうなら今日中にPR出します👴

**Comment by 0918nobita** [comment]
良さそうです！よろしくお願いします

**Comment by 0918nobita** [comment]
@hppRC ここでちょっとした GitHub の活用テクニックを紹介しておきます

Githubのkeywordを利用してPull Requestがマージ、クローズされたタイミングで関連するIssueも同時に閉じる | tackeyy.com
https://tackeyy.com/blog/posts/close-github-issue-after-pull_request-is-merged-or-closed

**Comment by 0918nobita** [comment]
↑ の方法で Issue がクローズされるようにすれば、Issue 側にもどの PR の影響で自動クローズされたのかログが残るので、あとから追跡がしやすいです

**Comment by hppRC** [comment]
追加しました！
ありがとうございますー！！
