### ISSUE TITLE
editorの各ファイルのimportの順番をsortしたい

### ISSUE THREAD

**Issue by hppRC** [knights-dev/knights#50]
- 各人によってimportの順番が違うのが辛いので、自動的にimport順をsortするようにしたい、したくない？
- (prettier-plugin-import-sort)[https://www.npmjs.com/package/prettier-plugin-import-sort]を試してみたけどpragmaまでsortされちゃって動かなくなる
- 本格的に開発する前に整えてしまいたいところ
- そんなに深く試していないので何かあれば教えてください

**Comment by 0918nobita** [comment]
すでに `simple-import-sort` eslint plugin 入れて ``eslint fix`` 時にソートまでされるようになってるはずです

**Comment by hppRC** [comment]
おおお申し訳ないです、確認不足でした…
huskyでpre-pushでhookしたりとかはする予定ありますか？

**Comment by 0918nobita** [comment]
今の所考えてないですね…
正直プルリク投げるときにチェックしてくれさえすればコードの品質は保てると思ってますし、
pre-commit フックを設定すると各々の git 周りの環境に干渉してしまってかえって DX が悪くなってしまいそうなので

**Comment by hppRC** [comment]
了解です！！
husky鬱陶しいですもんね...😇
