### ISSUE TITLE
.gitignoreについて

### ISSUE THREAD

**Issue by kirisaki** [knights-dev/knights#87]
概要
---
`.gitignore`に`.yarn`や`*.swp`、`*.swo`を追加したい。前者はこのプロジェクトに関わる人なら誰でも発生するディレクトリだが、後者はVim利用者のみ発生するファイルである。入れてしまってもよいか。多分Macの人も`.DS_Store`を入れたいと思っていると思う。

**Comment by loloiccl** [comment]
emacs では `*~` とかも?

**Comment by 0918nobita** [comment]
いいですね
あと `.vscode` も追加したいです (特に TypeScript のバージョンが VS Code 内部のものとズレたときにどうしても `.vscode/settings.json` が必要になってしまうので

**Comment by 0918nobita** [comment]
https://gitignore.io で、ある程度は .gitignore の内容を自動生成できます

例えば

- Visual Studio Code
- Vim
- Emacs

を選択してから生成させるとこんな感じになります → https://www.gitignore.io/api/vim,emacs,visualstudiocode

**Comment by kirisaki** [comment]
とりあえず入れちゃいましょ
